### PR TITLE
Issue #31 travis-ci integration and Issue #35 include markdown extra

### PR DESCRIPTION
**Pull request by treffynnon**
# Issue #31

I have attempted to get travis-ci builds to work. The tests are erroring out for me on both my development machine and up on travis-ci so I think perhaps there is a regression in the tests.

So here is the output of the travis-ci build: http://travis-ci.org/#!/treffynnon/phrozn/jobs/627500

travis-ci is now up and running for phrozn, but some of the assertions are not passing. So this should close issue #31, but may need additional work.
# Issue #35

Replaced the markdown parser with Markdown Extra.

### CODE REVIEW

**Comment by sasezaki** [comment]
Great! 
"InvalidArgumentException: You must not expect the generic exception class."
This failure seems invoked by PHPUnit 3.6's break.
https://twitter.com/#!/s_bergmann/status/163638051967471616
@farazdagi What's PHPUnit version for Phrozn develop ?

**Comment by farazdagi** [comment]
@treffynnon Thanks! Can you please resubmit your request against `dev` branch? We are using `master` branch to push versions into production, all development occurs in `dev` branch.

@sasezaki I will need to review 3.7 changelog, to see what version will be used as default for Phrozn development. Then plan to update the documentation.

**Comment by treffynnon** [comment]
@sasezaki it looks like @farazdagi is targeting PHPUnit 3.5 looking at the test output at http://test.phrozn.info - the PHPUnit version is in the page footer.

I hadn't noticed till now. So it looks like the tests might need some updating or the travis-ci configuration could be amended to downgrade the PHPUnit version before the build, but this is complicated. See https://github.com/lenada/travis-phpunit34/blob/master/.travis.yml from https://github.com/travis-ci/travis-ci/issues/406

**Comment by farazdagi** [comment]
@treffynnon I will update all tests and make sure they are passing, so that configuration changes you made are enough :)

**Pull request closed without merging**
