### PR TITLE
Use composer to pull in Markdown, Textile, and LESS parsers.

### PR DESCRIPTION
**Pull request by itafroma**
This is a rahash of #83, but with working tests. I'm somewhat new to GitHub pull requests: if there is a better way to correct someone else's PR, let me know and I'll resubmit it that way.

The changes in test files are mostly superficial: things like spacing, indentation, and capitalization in CSS hex colors brought on by updating the libraries to the latest versions using composer.

The changes in the textile output files are weird: the original files had incorrect element nesting and shouldn't have passed. Presumably there was a bug in the original Textile parser.

### CODE REVIEW

**Comment by farazdagi** [comment]
@itafroma Thanks for PR. I will review it and merge this weekend.

**Comment by sasezaki** [comment]
ping @farazdagi

**Comment by Goutte** [comment]
This PR is part of PR #100 too, by the way.

**Comment by Pawka** [comment]
Merged via #100 Thanks!

**Pull request closed without merging**
